#!/bin/bash

export PLATFORM_VERSION=11
export ANDROID_MAJOR_VERSION=r
export ARCH=arm64
export KBUILD_BUILD_USER=Kohei
export KBUILD_BUILD_HOST=Izumi
export SUBARCH=arm64
export ANDROID_MAJOR_VERSION=q
#export PATH="/home/anuragrai/.local/src/android_clang_prebuilt/bin:$PATH"
export PATH="/mnt/45A15FA43FC33C00/Kernel-Dev/android-kernel_toolchain/bin:$PATH"
export LLVM=1
export PATH="/usr/lib/ccache/bin/:$PATH"
export CCACHE_SLOPPINESS="file_macro,locale,time_macros"
export CCACHE_NOHASHDIR="true"
export CCACHE_DIR=/mnt/45A15FA43FC33C00/Kernel-Dev/ccache
export CROSS_COMPILE=aarch64-linux-gnu-
make O=out M21_defconfig -j$(nproc)
make O=out savedefconfig -j$(nproc)
