# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_SOC_EXYNOS9610) += \
	exynos9611-m21_swa_open_06.dtbo \
	exynos9611-m21_swa_open_00.dtbo

always		:= $(dtb-y) $(dtbo-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb *.dtbo
